trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  STORAGE_ACCOUNT_NAME: 'stdmgmtday8'
  CONTAINER_NAME: 'raw'
  BLOB_FILE_NAME: 'ce_brand_detail.csv'
  SQL_SERVER: 'minukserver.database.windows.net'
  DATABASE: 'dmgmt_day8'
  USERNAME: 'mc79857'
  PASSWORD: '여기에_비밀번호_입력'   # 🔒 절대 공개 저장소에 올리지 말 것
  TABLE_NAME: 'ce_brand_detail'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription connection name'  # Azure DevOps에 연결된 서비스 이름
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Downloading CSV file from Azure Blob Storage..."
      az storage blob download \
        --account-name $(STORAGE_ACCOUNT_NAME) \
        --container-name $(CONTAINER_NAME) \
        --name $(BLOB_FILE_NAME) \
        --file $(BLOB_FILE_NAME) \
        --auth-mode key

      echo "Uploading CSV data into Azure SQL Database..."
      sqlcmd -S $(SQL_SERVER) -d $(DATABASE) -U $(USERNAME) -P $(PASSWORD) -Q "
      BULK INSERT $(TABLE_NAME)
      FROM '$(System.DefaultWorkingDirectory)/$(BLOB_FILE_NAME)'
      WITH (
          DATA_SOURCE = 'MyBlobStore',
          FORMAT='CSV',
          FIRSTROW = 2,
          FIELDTERMINATOR = ',',
          ROWTERMINATOR = '0x0a'
      );"
  displayName: 'Load CSV from Blob into Azure SQL'

- script: echo "✅ Data load process completed successfully!"
  displayName: 'Confirm completion'
