# =====================================
# Azure DevOps Simple CI Pipeline
# Author: Minuk Choi (Steven)
# =====================================

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "🔧 Starting CI pipeline..."
  displayName: "Initialize pipeline"

- script: |
    echo "🧱 Building project..."
    echo "✅ Build successful - No Azure connection used"
  displayName: "Run local build"

- script: |
    echo "🧪 Running tests..."
    echo "✅ All tests passed!"
  displayName: "Run unit tests"

- script: echo "🚀 Deployment skipped (no Azure connection configured)"
  displayName: "Deploy (skipped)"
